environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

os:
  - Visual Studio 2015

shallow_clone: true

install:
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\MinGW\\bin;%PATH%"
  - pip install pytest

build: off

test_script:
  - "python run_ci.py"

artifacts:
    - path: 'make/install/*.exe'
      name: Distributions for Windows

deploy:
  provider: GitHub
  auth_token:
    secure: 79ZJS9bGVP+7P+00FDjBAsio7iAiXISHzTcedhTI1TRDo6R3oUkuhklPip2oevQW
  draft: false
  on:
    appveyor_repo_tag: true
    PYTHON: "C:\\Python34-x64"
